steps:
- name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
- name: "gcr.io/cloud-builders/yarn"
    args: ["test"]
- name: "gcr.io/cloud-builders/yarn"
    args: ["storybook:build"]
- name: "cp"
    args: ["app.yaml", "storybook-static/app.yaml"]
- name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "storybook-static"