steps:
    - name: node:10.15.1
      entrypoint: yarn
      args: ['install']
    - name: node:10.15.1
      entrypoint: yarn
      args: ['test']
    - name: node:10.15.1
      entrypoint: yarn
      args: ['build:storybook']
    - name: node:10.15.1
      entrypoint: yarn
      args: ['build:gcp']
    - name: gcr.io/cloud-builders/gcloud
      args: ['app', 'deploy', './storybook-static']