steps:
    - name: node:10.15.1
      entrypoint: yarn
      args: ['install']
    - name: node:10.15.1
      entrypoint: yarn
      args: ['test']
    - name: node:10.15.1
      entrypoint: yarn
      args: ['storybook:build']
    # - name: 'cp'
    #     args: ['app.yaml', 'storybook-static/app.yaml']
    # - name: 'gcr.io/cloud-builders/gcloud'
    #     args: ['app', 'deploy']
    #     dir: 'storybook-static'